### PR TITLE
Update self tests snapshots

### PR DESCRIPTION
**Pull request by zhongruige**
This PR updates self tests snapshots.

### CODE REVIEW

**Comment by zhongruige** [comment]
Looks like we're seeing the same results with two of the e2e tests as on https://github.com/woocommerce/qit-cli/pull/66

**Comment by Luc45** [comment]
This is weird, we can see it's passing on Woo: https://github.com/woocommerce/woocommerce/actions/runs/5752528579/job/15593734491#step:7:234

I'll run a single E2E test against Staging to get the Allure Test Report and see where it's failing exactly.

**Comment by Luc45** [comment]
The easiest solution would be to skip that test. I would only do that as a last resource, though. I wonder if this might be related to the tests that we are skipping for all E2E tests.

**Comment by zhongruige** [comment]
Thanks @Luc45! The PR fixing it was closed as it [resolved itself](https://github.com/woocommerce/woocommerce/pull/39367#issuecomment-1654609598), so wonder if it's flakiness we're seeing here.

**Comment by Luc45** [comment]
I see what's happening. We need to add the newly-added `filter-setter.php` mu-plugin that's part of the tests now. This is part of the test runner environment. I'll open a PR today.

**Comment by zhongruige** [comment]
> I see what's happening. We need to add the newly-added `filter-setter.php` mu-plugin that's part of the tests now. This is part of the test runner environment. I'll open a PR today.

Oh interesting, good catch!

**Review by Luc45 — APPROVED** [review]

**Pull request merged**
