### PR TITLE
Improve test orchestration for more powerful Compatibility Tests between plugins

### PR DESCRIPTION
**Pull request by Luc45**
## Read first

I've generated this PR description by feeding the git diff between this branch and trunk to an AI (Starting from 1, 2, 3, etc). This introduction and the testing instructions were written by me. I have manually reviewed the AI-generated description.

## Testing Instructions

I have added tests that mimick a compatibility test between two plugins and runs some assertions about the shared/isolated setup and teardown. I think the easiest way to test this is to run that test, and modify the existing test files if you want to test something else. Here's an example output of running it:

image

This test asserts that we first run the shared setups, we do a DB export, and then we iterate on each plugin of the test scenario, running their setup, test phases and teardown, then we import the DB dump before moving to the next plugin, to reset the state, and we run the setup, test and teardown of the second plugin. Finally, we run the shared teardown.

Feel free to change these tests such as removing the shared setup of one of the plugins, adding another plugin, etc.

- `cd _tests/orchestration`
- `qit switch local` (with the counterpart branch)
- `qit run:e2e woocommerce-amazon-s3-storage` (Just a random extension I've chosen for this test)

What's left to do: Update the documentation, which I'll do in a follow-up PR.

From now on, the rest of this PR is AI-generated and carefully reviewed by me.

## 1. Introduction of Environment Variables Option in E2E Command
**File Modified:**
- `RunE2ECommand.php`

**Changes:**
- Added a new `--env` option to the `run:e2e` command, allowing users to pass environment variables to the tests.
- Implemented a method `parse_env_vars` to handle and validate the environment variables provided.
- Environment variables are stored using `App::setVar('QIT_PW_ENV_VARS', $parsed_vars)` for later use.

**Implications:**
- Users can now pass custom environment variables directly when running E2E tests, enhancing flexibility and configurability.
- This is particularly useful for passing dynamic data or configuration options that tests might depend on.

## 2. Enhancements to E2E Test Scaffolding
**File Modified:**
- `ScaffoldE2ECommand.php`

**New Options:**
- `--with-shared` (`-s`): Includes shared setup examples when scaffolding E2E tests.
- `--with-teardown` (`-t`): Includes teardown examples in the scaffolding process.

**Changes:**
- The scaffolding process now conditionally includes additional setup and teardown files based on the options provided.
- Templates for these files have been added (e.g., `setup-sh.txt`, `shared-setup-js.txt`, `teardown-js.txt`, etc.).

**Implications:**
- Users have greater control over the scaffolding process, allowing them to include shared setups and teardowns as needed.
- This helps in creating more comprehensive test environments with minimal manual configuration.

## 3. Simplification of Configuration File Naming
**Files Modified:**
- `UpEnvironmentCommand.php`
- `EnvConfigLoader.php`
- Tests related to `EnvConfigLoader`

**Changes:**
- Configuration files are now expected to be named `qit.json` or `qit.yml` instead of `qit-env.json` or `qit-env.yml`.
- Override files are similarly renamed to `qit.override.json` or `qit.override.yml`.
- Updated help texts and error messages to reflect these changes.
- Adjusted test cases to align with the new naming convention.

**Implications:**
- Simplifies the naming convention for configuration files, making it more intuitive.
- Reduces potential confusion with file names and makes the CLI tool more user-friendly.

## 4. Introduction of Playwright Orchestration Class
**New File:**
- `PlaywrightOrchestration.php`

**Changes:**
- A new class `PlaywrightOrchestration` has been introduced to handle the orchestration of Playwright projects.
- It generates Playwright configuration dynamically based on the test information provided.
- The logic for creating test projects, handling dependencies, and setting up the execution order has been encapsulated within this class.

**Implications:**
- Improves code organization by separating orchestration logic from the runner.
- Allows for more complex test setups, including shared setups and teardowns, with proper dependency management.
- Enhances maintainability and scalability of the testing framework.

## 5. Refactoring of Playwright Runner
**File Modified:**
- `PlaywrightRunner.php`

**Changes:**
- Updated to use the new `PlaywrightOrchestration` class for generating test projects.
- Removed the old `make_projects` method and replaced it with a call to `$this->orchestration->make_projects($test_infos)`.
- Enhanced output formatting for better readability in the console, including color-coded status messages.

**Implications:**
- Delegates responsibility for project creation to the new orchestration class.
- Simplifies the runner code and focuses it on executing the tests rather than preparing them.
- Provides a clearer and more user-friendly output during test execution.

## 6. Removal of Direct Bootstrap Script Execution
**File Modified:**
- `E2ETestManager.php`

**Changes:**
- Removed the direct execution of `bootstrap.php` and `bootstrap.sh` scripts during the bootstrap phase.
- The test orchestration now handles setup and teardown through Playwright projects instead.

**Implications:**
- Encourages the use of Playwright for all test-related scripting, promoting consistency.
- Allows setup and teardown scripts to leverage Playwright's features, such as browser automation and advanced testing capabilities.
- Reduces reliance on shell and PHP scripts executed outside of the testing framework.

## 7. Updates to Scaffolding Templates
**Files Modified/Added:**
- New scaffolding templates like `setup-sh.txt`, `teardown-js.txt`, `shared-setup-js.txt`, etc.
- Removed `bootstrap-php.txt`.

**Changes:**
- The scaffolding templates now provide separate files for setup and teardown in both shell (`.sh`) and JavaScript (`.js`).
- Templates include comments and examples to guide users in creating their own setup and teardown scripts.
- The `mu-plugin.php` template remains for must-use plugin scenarios.

**Implications:**
- Offers a more organized structure for test scripts, separating concerns between setup, teardown, and the actual tests.
- Helps users quickly scaffold tests with the appropriate files and structure.
- Encourages best practices in test organization and execution flow.

## 8. Adjustments in Plugin and Theme Parsing
**File Modified:**
- `PluginsAndThemesParser.php`

**Changes:**
- Added logic to ensure the System Under Test (SUT) is correctly handled and forced to use the `test` action.
- Prevents overriding the SUT's action if it's specified in a configuration file.

**Implications:**
- Ensures that the main plugin or theme under test is always tested, regardless of other configurations.
- Avoids accidental misconfiguration that could lead to the SUT not being tested properly.

## 9. New Tests for Playwright Orchestration
**New File:**
- `PlaywrightOrchestrationTest.php`

**Changes:**
- Added a comprehensive test suite for the `PlaywrightOrchestration` class.
- Tests cover various scenarios, including different combinations of setup and teardown scripts across multiple plugins.

**Implications:**
- Improves the reliability of the testing framework by ensuring the orchestration logic works as intended.
- Facilitates future changes by providing a safety net through extensive test coverage.

## 10. Miscellaneous Updates
**Changes:**
- Updated console outputs and messages for better clarity and guidance.
- Minor code refactoring for better readability and maintainability.
- Adjusted snapshot tests to align with the new configuration and file naming conventions.

**Implications:**
- Enhances the overall user experience when using the CLI tool.
- Makes the codebase cleaner and easier to navigate for developers.

## Conclusion
The updates introduce significant improvements to the E2E testing workflow, providing greater flexibility, better organization, and enhanced capabilities. By leveraging the new `PlaywrightOrchestration` class and updating the scaffolding process, the framework now supports more complex testing scenarios with proper setup and teardown procedures.

**Recommendations:**
- **Update Documentation:** Ensure that all changes are reflected in your project's documentation, especially the new command options and configuration file names.
- **Review Test Suites:** Given the changes, it's advisable to review existing tests and adjust them if necessary to align with the new structure.
- **Communicate Changes:** If this tool is used by a team, communicate these updates to all team members to facilitate a smooth transition.

If you have any specific questions or need further clarification on any part of the changes, feel free to ask!

### CODE REVIEW

**Comment by zhongruige** [comment]
... that AI description is top notch! I really like the new files / files modified that it includes too. Nice!

**Comment by zhongruige** [comment]
This is really awesome @Luc45! Testing great for me so far.

Minor thing that is something we can follow up on in the future, but do you think we should include these in the assertion section (the script, teardown, database import/export etc) or hide them (potentially even just having them in an env setup section or similar instead):

Screenshot 2024-11-24 at 4 16 50 PM

**Comment by Luc45** [comment]
> do you think we should include these in the assertion section

This is a good question that I questioned myself as well.

On one hand, I'd like to keep it because this is permanent, whereas the Allure Report is saved for only 7 days, so if someone is looking at an older test run, that might be all they see.

On the other, we have to proxy PHP and Bash execution through a parametrized Playwright test, and this generates ugly names like "Running Bash Script" instead of "Plugin A Shared Setup Bash Script".

I think there's room for improvement there, I'm just not 100% certain how exactly. Do you think we should remove it while we figure it out?

**Comment by zhongruige** [comment]
> Do you think we should remove it while we figure it out

Good question! I lean a bit towards removing it while we figure out.

**Comment by Luc45** [comment]
@zhongruige I've improved the test assertions table, let me know what you think:

image

If that step/test generated output, you can click to view it:

image

Sorry for the late ping, I hope GitHub had a "Schedule Comment" feature, I hope you only see this Monday morning :)

**Comment by zhongruige** [comment]
Ohh nice, I really like that improvement @Luc45! Especially being able to click in to view more, that is great 🙌

**Comment by Luc45** [comment]
> Ohh nice, I really like that improvement @Luc45! Especially being able to click in to view more, that is great 🙌

Thanks, I actually just need to make a little adjustment for nested assertions as those inside `test.describe`, and I'm also trying my best to make sure the tests are displayed in the order they are executed, which is not taken for granted in PW given the parallel nature of it (even though we run in serial).

**Comment by zhongruige** [comment]
Oh nice, that sounds great!

**Comment by Luc45** [comment]
@zhongruige This should be taken care of now, and ready for review. We can jump in a call to go through it/review it if you'd like.

**Review by zhongruige — APPROVED** [review]
Happy to add my approval to this! It's been working great for me, thank for the great work on this @Luc45!

**Pull request merged**
